// Generated by https://quicktype.io

export interface TopLevel {
  nav_data:                  { [key: string]: string }[];
  home_mobile_data:          HomeMobileDatum[];
  home_desktop_data:         HomeDesktopDatum[];
  getintouch_mobile_data:    GetintouchDatum[];
  getintouch_desktop_data:   GetintouchDatum[];
  maintainable_mobile_data:  Datum[];
  maintainable_desktop_data: Datum[];
  whatwedo_mobile_data:      Datum[];
  whatwedo_desktop_data:     Datum[];
}

export interface GetintouchDatum {
  id:                   number;
  img_banner:           string;
  img_banner_alt:       string;
  title:                string;
  title_2:              string;
  title_3:              string;
  text_1:               string;
  text_2:               string;
  text_3?:              string;
  contact_img_1:        string;
  contact_img_1_alt:    string;
  contact_img_1_mail:   string;
  contact_img_2:        string;
  contact_img__2_alt:   string;
  contact_img_2_mail:   string;
  contact_img_3:        string;
  contact_img__3_alt:   string;
  contact_img_3_mail:   string;
  bottom_right_text?:   string;
  getintouch_logo?:     string;
  getintouch_logo_alt?: string;
}

export interface HomeDesktopDatum {
  logo:                  string;
  logo_alt:              string;
  whatwedo_card:         string;
  whatwedo_card_alt:     string;
  maintainable_card:     string;
  maintainable_card_alt: string;
  getintouch_card:       string;
  getintouch_card_alt:   string;
  bottom_text:           string;
}

export interface HomeMobileDatum {
  logo:                    string;
  logo_alt:                string;
  whatwedo_banner:         string;
  whatwedo_banner_alt:     string;
  maintainable_banner:     string;
  maintainable_banner_alt: string;
  getintouch_banner:       string;
  getintouch_banner_alt:   string;
}

export interface Datum {
  id:                     number;
  img_banner:             string;
  img_banner_alt:         string;
  title:                  string;
  title_2:                string;
  title_3:                string;
  text_1:                 string;
  text_2:                 string;
  text_3?:                string;
  bottom_right_text?:     string;
  maintainable_logo?:     string;
  maintainable_logo_alt?: string;
  whatwedo_logo?:         string;
  whatwedo_logo_alt?:     string;
}
