// Generated by https://quicktype.io

export interface myInterface {
  components: Components;
}

export interface Components {
  navbar: { [key: string]: string };
  home_mobile: HomeMobile;
  home_desktop: HomeDesktop;
  getintouch_mobile: GetintouchDesktop;
  getintouch_desktop: GetintouchDesktop;
  maintainable_mobile: GetintouchDesktop;
  maintainable_desktop: GetintouchDesktop;
  whatwedo_mobile: GetintouchDesktop;
  whatwedo_desktop: GetintouchDesktop;
}

export interface GetintouchDesktop {
  img_banner: string;
  img_banner_alt: string;
  title: string;
  title_2: string;
  title_3: string;
  text_1: string;
  text_2: string;
  text_3: string;
  contact?: Contact[];
  bottom_right_text?: string;
  getintouch_logo?: string;
  getintouch_logo_alt?: string;
  maintainable_logo?: string;
  maintainable_logo_alt?: string;
  text_4?: string;
  whatwedo_logo?: string;
  whatwedo_logo_alt?: string;
}

export interface Contact {
  id: string;
  src: string;
  alt: string;
  email: string;
  title: string;
}

export interface HomeDesktop {
  logo: string;
  logo_alt: string;
  whatwedo_card: string;
  whatwedo_card_alt: string;
  maintainable_card: string;
  maintainable_card_alt: string;
  getintouch_card: string;
  getintouch_card_alt: string;
  bottom_text: string;
}

export interface HomeMobile {
  logo: string;
  logo_alt: string;
  whatwedo_banner: string;
  whatwedo_banner_alt: string;
  maintainable_banner: string;
  maintainable_banner_alt: string;
  getintouch_banner: string;
  getintouch_banner_alt: string;
  bottom_text: string;
}
