// Generated by https://quicktype.io

export interface Components {
  components: any;
  navbar:               { [key: string]: string };
  home_mobile:          HomeMobile;
  home_desktop:         HomeDesktop;
  getintouch_mobile:    { [key: string]: string };
  getintouch_desktop:   { [key: string]: string };
  maintainable_mobile:  { [key: string]: string };
  maintainable_desktop: { [key: string]: string };
  whatwedo_mobile:      { [key: string]: string };
  whatwedo_desktop:     { [key: string]: string };
}

export interface HomeDesktop {
  logo:                  string;
  logo_alt:              string;
  whatwedo_card:         string;
  whatwedo_card_alt:     string;
  maintainable_card:     string;
  maintainable_card_alt: string;
  getintouch_card:       string;
  getintouch_card_alt:   string;
  bottom_text:           string;
}

export interface HomeMobile {
  logo:                    string;
  logo_alt:                string;
  whatwedo_banner:         string;
  whatwedo_banner_alt:     string;
  maintainable_banner:     string;
  maintainable_banner_alt: string;
  getintouch_banner:       string;
  getintouch_banner_alt:   string;
}
